NDefines.NCharacter.FERTILITY_BASE_MULT = 0.09
NDefines.NCharacter.SECONDARY_SPOUSE_FERTILITY_MULT = 0.09
NDefines.NEngine.EVENT_PROCESS_OFFSET = 350
NDefines.NEngine.COURTIER_EVENT_PROCESS_OFFSET = 650
NDefines.NEngine.COURT_PRUNE_SIZE = 1
NDefines.NEngine.PRUNE_MINIMAL_AGE = 1